### ISSUE TITLE
Spread bindings broken with backslashes

### ISSUE THREAD

**Issue by roblabla** [sagiegurari/duckscript#109]
**Describe the bug**
It appears spread binding operator (`%{}`) doesn't work properly, returning an empty string even when the variable contains data that gets printed out when using the normal binding operator (`${}`). I was only able to reproduce this on windows again, maybe it's again some weird `\` encoding behavior?

**To Reproduce**

Run the below code sample in duckscript (I went through cargo-make, making a simple reproduce task, but it probably works everywhere).

If the patches are changed to only contain linux-like paths (e.g.all `\\` are replaced with `/`), then the spread operator will work properly.

**Code Sample**
```
patches = set "C:\\Users\\roblabla\\Documents\\SunriseOS\\rust-patches\\0001-Create-workspace-remove-unneeded-deps-in-lockfile.patch C:\\Users\\roblabla\\Documents\\SunriseOS\\rust-patches\\0002-Add-sunrise.patch"
echo ${patches}
echo %{patches}
```

**Comment by roblabla** [comment]
So I just looked at the code, and something feels weird here. I don't understand why, in the case of a spread operator, [we go through parse_arguments](https://github.com/sagiegurari/duckscript/blob/master/duckscript/src/expansion.rs#L111). This feels super off because we're parsing something that was potentially already parsed. If I do

```
patches = set "\\"
echo %{patches}
```

Then "\\" will be parsed once as an argument to set (leaving a string containing a literal backslash), and then once again when going through the spread operator (which will cause an error because we have a string that ends with a `\`).

Also while investigating this, I've tried a simple rule to double the amount of `\`, and it also failed to work:

```
patches = set "C:\\Users"
echo Before: ${patches}
patches = replace ${patches} "\\" "\\\\"
echo After: ${patches}
```

What's really weird though, is that replacing a `\\` with a ` ` will work properly:


```
patches = set "C:\\Users"
echo Before: ${patches}
patches = replace ${patches} "\\" " "
echo After: ${patches}
```

😕

**Comment by sagiegurari** [comment]
thanks for all the info. I'll investigate

**Comment by sagiegurari** [comment]
@roblabla fixed this one.
i actually do need to parse it again in order to split the arguments correctly, for example if they have quotes and so on...
but what i added is the ability to reparse meaning i add control chars as is and not add any special login on top.

i'm releasing it now and also releasing a new cargo-make version for it.
reason is, that these changes feel pretty risky, so want to keep it with a minor version change and not patch.

**Comment by sagiegurari** [comment]
duckscript and cargo-make versions released with the fixes.

**Comment by pratikpparikh** [comment]
this seems to be an issue again I can't produce windows path in duckscript get control character erro.  @sagiegurari  can you help?

**Comment by sagiegurari** [comment]
@pratikpparikh any chance you can provide sample script?

**Comment by pratikpparikh** [comment]
i was able to create the path by using \\\\ instead of using \\.  Thank you
