### ISSUE TITLE
Support arrays in "exec" invocation

### ISSUE THREAD

**Issue by berkus** [sagiegurari/duckscript#133]
I'm using duckscript for cargo-make scripting and sometimes I need to run something like 

```
'''
exec ${CMD} ${CMD_ARGS} someFile
'''
```

exec attempts to put all CMD_ARGS into a single argument and of course the command fails.

it'd be nice if there was either a flag to exec to support this or at least support for array invocation like

```
'''
args = split ${CMD_ARGS} " "
exec ${CMD} ${args} someFile
'''
```

duckscript 0.5.0 in cargo-make 0.32.5

**Comment by sagiegurari** [comment]
Did you try

```sh
exec ${CMD} %{CMD_ARGS} someFile
```

**Comment by berkus** [comment]
No, I didn't find documentation for that. If it works - perfect!

**Comment by berkus** [comment]
Ah, found it in https://github.com/sagiegurari/duckscript#using-variables---spread-binding

sorry, slipped my eye!
