### ISSUE TITLE
Add while() loop

### ISSUE THREAD

**Issue by Kreyren** [sagiegurari/duckscript#138]
Tracking relevant to https://github.com/sagiegurari/cargo-make/issues/486#issuecomment-723544644

**Comment by sagiegurari** [comment]
will do

**Comment by sagiegurari** [comment]
@Kreyren this is now implemented in the 0.6.9 dev branch:
https://github.com/sagiegurari/duckscript/blob/0.6.9/docs/sdk.md#std__flowcontrol__While

**Comment by Kreyren** [comment]
will check, thanks for the work!
