### ISSUE TITLE
Linting software

### ISSUE THREAD

**Issue by Kreyren** [sagiegurari/duckscript#139]
Proposing implementing upstream-maintained linting software for duckscript.

Tracking relevant to https://github.com/sagiegurari/cargo-make/issues/486

**Comment by sagiegurari** [comment]
I might be able to do something basic like checking that i'm able to parse the file.
since the language has almost nothing and most of the stuff is in the commands, full linting support or more complex parsing checks might not be possible.

**Comment by Kreyren** [comment]
> I might be able to do something basic like checking that i'm able to parse the file.

That would be sufficient for now imho.

**Comment by sagiegurari** [comment]
linter is now available in the 0.6.9 branch.
simply run
```sh
duck --lint somefile.ds
```

it checks the script parses correctly and few naming conventions.
