### ISSUE TITLE
Silent spawn

### ISSUE THREAD

**Issue by AntonOellerer** [sagiegurari/duckscript#142]
Hey,
Thank you a lot for all of the work you put into this, this seems like a really useful language.
One thing I came across when using duckscript together with [cargo-make](https://github.com/sagiegurari/cargo-make/) is when I am starting a background process, like a server for system tests.
Is there any way to spawn a process and ignore its output? 
When doing the system tests, I am sure that the server runs correctly, so I am not really interested in what it has to say.
### Feature Description
A flag to run `spawn` processes silently.
An alternative would be something like the ampersand in bash.

### Describe The Solution You'd Like
When I start a process with `spawn`, its output does not go to the terminal.

### Code Sample

```
pid = spawn --silent makers start-server
-------------------------
pid = exec makers start-server &
```

**Comment by sagiegurari** [comment]
strange, i was pretty sure spawn doesn't print anything to the console.

**Comment by AntonOellerer** [comment]
Maybe I messed something up, but in [this](https://github.com/sagiegurari/duckscript/issues/108) issue, this behaviour is described as well.

**Comment by sagiegurari** [comment]
probably i just don't remember it right :D
i'll check it out and if needed i'll add a new flag.

**Comment by sagiegurari** [comment]
@AntonOellerer this is now supported using a --slient flag.
Thanks a lot for opening the issue.
cargo-make will have this new version once i bump it there (today/tomorrow).
