### ISSUE TITLE
Exit does not return given exit code

### ISSUE THREAD

**Issue by AntonOellerer** [sagiegurari/duckscript#144]
Hey,
While further using duckscript, I ran into a problem with the `exit` command.
### Describe The Bug
As I understood it, `exit` exits the session returning the code supplied, but it seems as if always 0 is returned from the script execution.
### To Reproduce
```console
[test@ducktest]$ duck
exit 1
[test@ducktest]$ echo $?
0
```
Also happens if you run it from a file, so e.g.
```console
[test@ducktest]$ echo "exit 1" > test.ds && duck test.ds
[test@ducktest]$ echo $?
0
```

**Comment by sagiegurari** [comment]
right, i think its an issue i forgot to fix.
for a workaround, you can do assert_fail instead

**Comment by AntonOellerer** [comment]
Thank you!

**Comment by AntonOellerer** [comment]
During further experimenting, we also discovered that, if we set `exit_on_error true` at the beginning of our script, the script does not exit with an nonzero exit code either fyi

**Comment by sagiegurari** [comment]
ya, i set that by default as true when running in cargo make

**Comment by sagiegurari** [comment]
@AntonOellerer this is now supported, not sure why i didn't do it before :)
Thanks a lot for opening the issue.
cargo-make will have this new version once i bump it there (today/tomorrow).
