### ISSUE TITLE
Include Cargo.lock in repository

### ISSUE THREAD

**Issue by jirutka** [sagiegurari/duckscript#146]
Please remove `Cargo.lock` from .gitignore and include it in the repository (or provide release source tarball with Cargo.lock included) – it’s important to get reproducible builds (not just) when packaging duckscript in a Linux distribution.

**Comment by sagiegurari** [comment]
I usually don't like doing that. it causes dependecy patches not being pushed. i agree that means that new builds can be different.

however

1. i create prebuilt packages
2. if you depend on duckscript in your project, you have your own lock file and dependency lock files are not used.

so i would like to understand more the use case where the lock file is needed in this repo

**Comment by jirutka** [comment]
> it causes dependecy patches not being pushed.

It causes that exactly the same dependency versions are used each time you build the project from the given commit. It’s up to you to regularly update Cargo.lock to get the latest patches.

> so i would like to understand more the use case where the lock file is needed in this repo

My use case is packaging duckscript in Alpine Linux. It’s important to ensure that the package with a specific version is always built from the same sources and dependencies, at any time. Now I had to generate Cargo.lock myself and include it in the aports repository ([here](https://github.com/alpinelinux/aports/tree/master/testing/duckscript)), which is suboptimal.

**Comment by sagiegurari** [comment]
I didn't know it was packaged in any linux distro.
So i'll add that cargo lock file and release a new version with it, but if you can would it be possible for you to submit a documentation PR which explains how to install it in alpine?

**Comment by sagiegurari** [comment]
@jirutka waiting for feedback :)

**Comment by jirutka** [comment]
> So i'll add that cargo lock file and release a new version with it

Thanks! However, I don’t understand why did you add create 0.7.1 as a branch…?

>  if you can would it be possible for you to submit a documentation PR which explains how to install it in alpine?

See #148.

**Comment by sagiegurari** [comment]
i always create a dev branch before pushing to master. I'll merge it soon

**Comment by jirutka** [comment]
I understand this, I just find it confusing to use the same naming scheme for branches as for release tags.

**Comment by sagiegurari** [comment]
i delete those before publishing a new release so there is no conflict.

**Comment by sagiegurari** [comment]
released to master with a new version including the lock file.
thanks for your work on publishing it to alpine :)

**Comment by jirutka** [comment]
Great, I just bumped the package to 0.7.1.

You're welcome!
