### ISSUE TITLE
run test in win10 failed, because no have echo exe in there.

### ISSUE THREAD

**Issue by umaYnit** [sagiegurari/duckscript#159]
### Describe The Bug

run test in win10, the test case `sdk::std::process::exec::mod_test::run_with_output` will failed.
It is because although the echo command can be used in the command line on windows, it is not actually an application like linux, but a part of cmd.exe.

### Error Stack

```console
The error stack trace
```

### Code Sample

```rust
/// paste code here
```

**Comment by sagiegurari** [comment]
thanks a lot. I'll probably switch to something else for windows.

**Comment by umaYnit** [comment]
use #[cfg(target_os = "windows")] to write separately?

**Comment by umaYnit** [comment]
just add `cmd /c` in front of `echo` like this: ` "out = exec cmd /c echo 1 2 3",`

**Comment by sagiegurari** [comment]
strange the CI is passing.
maybe for windows i'll run "xcopy /?" or something...

**Comment by umaYnit** [comment]
So why not use cmd or powershell to execute it?  the following test return code program also use it, like:
```Rust
const COMMAND_RUNNER: &str = if cfg!(windows) { "cmd /c" } else { "" };

#[test]
fn run_get_exit_code() {
    let script = &format!("out = exec --get-exit-code {} exit 42", COMMAND_RUNNER);

    test::run_script_and_validate(
        vec![create("")],
        script,
        CommandValidation::Match("out".to_string(), "42".to_string()),
    );
}
```

**Comment by sagiegurari** [comment]
how about a PR? since you got windows, that would really help.
on the way there are few tests written in duckscript (i got a duckscript test runner).
checkout: https://github.com/sagiegurari/duckscript/tree/master/test/std/process

there is a duckscript is_windows command that can be used.

**Comment by umaYnit** [comment]
> how about a PR? since you got windows, that would really help.

It's my pleasure. I also got a lot of help from cargo-make and duckscipt.
> on the way there are few tests written in duckscript (i got a duckscript test runner).
> checkout: https://github.com/sagiegurari/duckscript/tree/master/test/std/process
> there is a duckscript is_windows command that can be used.

I saw them, and what should I do?

**Comment by sagiegurari** [comment]
I am assuming those fail as well on your env, so we could do something like that to fix them:

```sh
fn test_echo_with_output
    command = set echo
    if is_windows
        command = set "cmd /c echo"
    end
    output = exec %{command} hello world

   .........
end
```

**Comment by umaYnit** [comment]
Got it,  I will test it

**Comment by Red-Teapot** [comment]
From my experience, some tests still fail in Windows 10 for the same reason.

Here's a list of Rust tests that failed:
```
sdk::std::process::exec::mod_test::run_no_output
sdk::std::process::exec::mod_test::run_no_output_with_fail_on_error_valid
sdk::std::process::exec::mod_test::run_with_output
sdk::std::process::spawn::mod_test::run_valid
sdk::std::process::spawn::mod_test::run_valid_silent
sdk::std::process::watchdog::mod_test::run_with_retries
sdk::std::process::watchdog::mod_test::run_without_retries
utils::exec::exec_test::exec_valid
```

For Duckscript tests, it fails on `[./test/std/process/exec_test.ds][test_echo_with_output]` for me. I'd expect that tests for exec, spawn and watchdog would fail too.

So perhaps this needs reopening? Or was there a fix that I somehow missed?

**Comment by sagiegurari** [comment]
right. makes sense.
