### ISSUE TITLE
How about support  Decimal to Hex convert

### ISSUE THREAD

**Issue by umaYnit** [sagiegurari/duckscript#165]
### Feature Description
Decimal to Hex convert

### Describe The Solution You'd Like
I want to handle some hex data operation, and the lib `meval` duckscript use not support hex, so I need to convert hex  to decimal and then do some calc.

**Comment by sagiegurari** [comment]
i'm open for new operations hex<->number
you feel you can submit a PR? or you would like me to implement something?

**Comment by umaYnit** [comment]
I want to try a PR
