### ISSUE TITLE
Operate on a map of JSON objects with unknown structure

### ISSUE THREAD

**Issue by asvln** [sagiegurari/duckscript#175]
### Feature Description
I can access JSON object keys/values by name through `myjson.keyname` but it would be nice to be able to load and parse a JSON file when I do not know the key names of the objects I am accessing... such as with this structure:

```json
{
  "unknown_a": {
    "status": "standard",
    "groups": [
      "a",
      "b"
    ]
  },
  "unknown_b": {
    "status": "non-standard",
    "groups": []
  }
}
```
### Describe The Solution You'd Like
`json::Parse` converts the JSON arrays into `std::collections::Array`, can we parse any JSON data structure as a map to be able to implement the respective `std::collections::Map` commands and be able to iterate over the map with `std::flowcontrol::ForIn`?

### Code Sample
```json
{
    "type_1": {
        "number": 500,
        "array": [1, 2, 3]
    },
    "type_2": {
        "number": 200,
        "array": [1, 2, 3]
    }
}
```
```rust
object = json_parse *json above*

assert_eq ${object} [OBJECT]
assert_eq is_map ${object}

for o in ${object}
    echo ${o}.number
    echo ${o}.array[1]
end
```

I can work on a PR for this if something like this can fit into the scripting framework and would be invited into the `std` library.

**Comment by sagiegurari** [comment]
@asvln thanks for the suggestion.
currently parse json doesn't create any arrays/maps at all actually. main reason is that, arrays/maps need to be released and you can easily leak memory if you don't.

if we are to do something like return a map/array handle from the parse (based on if the json is map/array/value) we need also a new release command. maybe... release_collection_deep which will release the map/array, go over items, if they are handles also release those and so on...

i would also create a flag on the parse command so it would return something different.

does it make sense?

**Comment by asvln** [comment]
@sagiegurari, that makes perfect sense. I will begin working on a PR with this approach.

**Comment by sagiegurari** [comment]
if you need help feel free to say so. also if you need me to do parts, tell me, for example the deep release for collections.

**Comment by asvln** [comment]
Apologies, life took hold.

I did take a look at the repo and think I know how to implement this, but I would like to try to figure it out myself for learning purposes before inquiring for help. However it still might be some time as my life is still hectic.

**Comment by sagiegurari** [comment]
no rush. private life comes first. always.

**Comment by sagiegurari** [comment]
seems that release_collection_deep is not really needed since i had a recursive flag on the current release command.
i am just fixing a missing support for set data structures, but that one is already there.

i'll take a look at implementing the json objects as you asked for and will update here.

**Comment by sagiegurari** [comment]
@asvln sorry it took so long. only today i got a chance to take a look at it.
i implemented the json_parse command to have a new optional flag (--collection) which instead of setting up the vars, it will return map/array handle (or primitive value) so you can use the maps/arrays commands to inspect and use the data instead.
at the end you should use the release with the --recursive to free the memory.

**Comment by sagiegurari** [comment]
i still need to implement the json_encode to work on such data and than i'll release a new version once done.

**Comment by sagiegurari** [comment]
had a bit more time now and finished the encode. once CI passes i'll release a new duckscript version.
basically for parse and encode you add the --collection flag (for encode also you pass the value, not var name, see tests/docs) and it will work.

**Comment by sagiegurari** [comment]
released

**Comment by asvln** [comment]
This is great, and I learned a lot in my attempts/seeing your implementation.

Thank you!
