### ISSUE TITLE
Add wildcard support to cp

### ISSUE THREAD

**Issue by r12f** [sagiegurari/duckscript#192]
### Feature Description
Currently cp doesn't support wildcard. With wildcard support, it will make copying multiple files much easier.

### Describe The Solution You'd Like
Say, we can an folder which contains a.exe, a.pdb, b.exe and b.pdb, and we would like to copy the exe file into a folder named bin, while pdb file into a folder named symbols.

Currently this is what we needs to do:

```duckscript
cp a.exe bin/a.exe
cp b.exe bin/b.exe
cp a.pdb symbols/a.pdb
cp b.pdb symbols/b.pdb
```

With wildcard support, it will be much easier:

```duckscript
cp *.exe bin/
cp *.pdb symbols/
```

### Code Sample
Code sample is the same as above.

**Comment by sagiegurari** [comment]
@r12f this is now implemented in the 0.8.5 branch. you can see a new command called glob_cp (also cp_glob) that can be used.

see api doc:
https://github.com/sagiegurari/duckscript/blob/0.8.5/docs/sdk.md#std__fs__CPGlob

would love some feedback if you have any

**Comment by r12f** [comment]
Awesome! Thanks a lot! And may I use it in cargo-make now? I will definitely upgrade and try it out.

**Comment by sagiegurari** [comment]
it should work, but im going to release a new cargo make in a few hours.

**Comment by sagiegurari** [comment]
@r12f might postpone the cargo-make release, but if you reinstall cargo-make it should pick up the latest duckscript version and should hopefully work.
if you have an issue with that, just open/reopen an issue. I would love to get some feedback if it works well.
