### ISSUE TITLE
glob_cp cannot handle full path correctly

### ISSUE THREAD

**Issue by r12f** [sagiegurari/duckscript#197]
### Describe The Bug
If we use full file path in glob_cp, it will try to create a unexpected directory and throw error.

### To Reproduce
I am using it in the latest cargo-make (build from cargo install), and found it with the code shown in the code example below.

And here is the detailed error:
![image](https://user-images.githubusercontent.com/1533278/133297868-e4a2cf10-2d52-473c-ac5f-b8dce478180b.png)

### Error Stack
Not a crash, so there is no stack for it. Please let me know, how to grab it and I can help.

```console
N/A
```

### Code Sample

```rust
[tasks.pack-symbols]
description = "Pack symbol files."
script_runner = "@duckscript"
script = '''
glob_cp "X:\\Code\\rnp\\target\\x86_64-pc-windows-msvc\\debug\\*.pdb" "X:\\Code\\rnp\\publish\\x86_64-pc-windows-msvc\\symbols"
'''
```

**Comment by sagiegurari** [comment]
oh, right. i wrote it thinking about relative paths only. good point

**Comment by sagiegurari** [comment]
@r12f i believe this is now fixed
