### ISSUE TITLE
cargo make failed 

### ISSUE THREAD

**Issue by hdqb** [sagiegurari/duckscript#199]
I installed it failed, I tried searching around stackoverflow still can't solve the `cargo make` error.
first error about android
`[2021-09-23T11:55:50Z INFO  cargo_ndk::cli] Building x86_64 (x86_64-linux-android)
   Compiling adder v0.1.0 (/Volumes/workspace/FLUTTER/projects/flutterust/native/adder)
   Compiling adder-ffi v0.1.0 (/Volumes/workspace/FLUTTER/projects/flutterust/native/adder-ffi)
error: linking with `/Users/hdqb/Library/Android/sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/darwin-x86_64/bin/x86_64-linux-android29-clang` failed: exit status: 1
  |
  = note: "/Users/hdqb/Library/Android/sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/darwin-x86_64/bin/x86_64-linux-android29-clang" "-Wl,--version-script=/var/folders/tz/7y0m3lms51x72cd154qvf3j80000gp/T/rustcb6AqhS/list" "-Wl,--allow-multiple-definition" "-m64" "/Volumes/workspace/FLUTTER/projects/flutterust/target/x86_64-linux-android/debug/deps/adder_ffi.3aytt3lqjjig5tel.rcgu.o" "/Volumes/workspace/FLUTTER/projects/flutterust/target/x86_64-linux-android/debug/deps/adder_ffi.1nbnkmbl2ld3icra.rcgu.o" "-Wl,--as-needed" "-L" "/Volumes/workspace/FLUTTER/projects/flutterust/target/x86_64-linux-android/debug/deps" "-L" "/Volumes/workspace/FLUTTER/projects/flutterust/target/debug/deps" "-L" "/Users/hdqb/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-linux-android/lib" "-Wl,-Bstatic" "/Volumes/workspace/FLUTTER/projects/flutterust/target/x86_64-linux-android/debug/deps/libadder-ec514e28d295f9a0.rlib" "-Wl,--start-group" "/Users/hdqb/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-linux-android/lib/libstd-2129c9a05f9454e7.rlib" "/Users/hdqb/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-linux-android/lib/libpanic_unwind-3535b579ca8ecc3f.rlib" "/Users/hdqb/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-linux-android/lib/libminiz_oxide-6f27a6fe87753869.rlib" "/Users/hdqb/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-linux-android/lib/libadler-600a9911ec2135bd.rlib" "/Users/hdqb/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-linux-android/lib/libobject-ee64a54f6cde973d.rlib" "/Users/hdqb/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-linux-android/lib/libaddr2line-8bab438bf3d39fa5.rlib" "/Users/hdqb/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-linux-android/lib/libgimli-3455b802a2298bcc.rlib" "/Users/hdqb/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-linux-android/lib/libstd_detect-9182f91556cbf04b.rlib" "/Users/hdqb/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-linux-android/lib/librustc_demangle-0fce61729445b783.rlib" "/Users/hdqb/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-linux-android/lib/libhashbrown-aa5cc9a80e6e3405.rlib" "/Users/hdqb/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-linux-android/lib/librustc_std_workspace_alloc-b516c2acfe98ecff.rlib" "/Users/hdqb/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-linux-android/lib/libunwind-e835a0450b9c2cd5.rlib" "/Users/hdqb/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-linux-android/lib/libcfg_if-f2d4541f48dac780.rlib" "/Users/hdqb/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-linux-android/lib/liblibc-3aa40c1e24f1127d.rlib" "/Users/hdqb/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-linux-android/lib/liballoc-d26ee6f2329afd09.rlib" "/Users/hdqb/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-linux-android/lib/librustc_std_workspace_core-d81fa4aed4b99dc8.rlib" "/Users/hdqb/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-linux-android/lib/libcore-44c6f4482d73ad2c.rlib" "-Wl,--end-group" "/Users/hdqb/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-linux-android/lib/libcompiler_builtins-cc10ede4dd1b1508.rlib" "-Wl,-Bdynamic" "-ldl" "-llog" "-lgcc" "-lc" "-lm" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/Users/hdqb/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-linux-android/lib" "-o" "/Volumes/workspace/FLUTTER/projects/flutterust/target/x86_64-linux-android/debug/deps/libadder_ffi.so" "-Wl,--gc-sections" "-shared" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs"
  = note: ld: error: unable to find library -lgcc
          clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: could not compile `adder-ffi` due to previous error
[2021-09-23T11:55:51Z INFO  cargo_ndk::cli] If the build failed due to a missing target, you can run this command:
[2021-09-23T11:55:51Z INFO  cargo_ndk::cli] 
[2021-09-23T11:55:51Z INFO  cargo_ndk::cli]     rustup target install x86_64-linux-android
[cargo-make][1] VERBOSE - Output: Ok(
    Output {
        status: ExitStatus(
            ExitStatus(
                25856,
            ),
        ),
        stdout: "",
        stderr: "",
    },
)
[cargo-make][1] ERROR - Error while executing command, exit code: 101
[cargo-make][1] WARN - Build Failed.
[cargo-make] ERROR - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.
`

ios `cargo lipo` error

`
[ERROR cargo_lipo] Did not find any packages with a `staticlib` target, considered []
`

**Comment by sagiegurari** [comment]
this issue is not related to cargo-make and definitely not to duckscript.
your build error is: "unable to find library -lgcc"
