### ISSUE TITLE
Feature Request - echo Colored Text

### ISSUE THREAD

**Issue by grbd** [sagiegurari/duckscript#203]
### Feature Description
Would or is it possible to echo colored text within duckscript?
So far I've tried echoing \033[2;31;43m to change the terminal color without any luck

**Comment by sagiegurari** [comment]
awesome idea, question is how to make it simple to use

**Comment by grbd** [comment]
I'm afraid I don't know much about the duckscript language
but I'd guess it'd involve adding wrappers around https://crates.io/crates/colored

I have been looking into rust-script as well as an alternative
but then run into this problem - https://github.com/fornwall/rust-script/issues/23

**Comment by sagiegurari** [comment]
didn't mean how to implement, more like how to use.
for example, should it be a new command or reuse echo, how are colors provided in the input, so on...

**Comment by grbd** [comment]
Maybe something a bit like
```
color_string_example = array ${styles.color_red} Hello ${styles.color_normal} World
echo color_string_example: ${color_string_example}
```

Not quite sure of the limits of the string concatenation within duckscript, you'd also have to consider combining multiple styles. I suspect the way colored works currently is by wrapping strings with a beginning and ending ansi characters or perhaps something else for windows to colour individual strings.

**Comment by sagiegurari** [comment]
Added new print and println commands which support color, background color and styling.
You can see the docs at:

* [print](https://github.com/sagiegurari/duckscript/blob/master/docs/sdk.md#std__Print)
* [println](https://github.com/sagiegurari/duckscript/blob/master/docs/sdk.md#std__Println)

Example:

```sh
print --color red --background-color green --style italic --style bold my text
println --color blue --background-color bright_yellow more text
```

**Comment by grbd** [comment]
Thats very useful, thanks
