### ISSUE TITLE
Using multiple backslashes results in only a single one

### ISSUE THREAD

**Issue by Blightbuster** [sagiegurari/duckscript#237]
### Describe The Bug
Using multiple backslashes results in only a single one
This is really annoying when trying to access files in a WSL as the path to it is:
`\\wsl$\Ubuntu\`

### To Reproduce
```sh
echo \\\\
```
Result:
> \\

Expected result:
> \\\\

**Comment by sagiegurari** [comment]
@Blightbuster thanks a lot for find that. pretty critical bug. I just pushed a fix for it on the development branch so you won't see it in cargo-make just yet, but soon.

**Comment by sagiegurari** [comment]
this is now released. if you reinstall cargo-make you should have the fix.

**Comment by Blightbuster** [comment]
I just noticed, that this issue was also discovered earlier but not properly recognized as such in [this](https://github.com/sagiegurari/duckscript/issues/109#issuecomment-639562773) comment.

**Comment by sagiegurari** [comment]
i added more tests to ensure this won't happen, but its always tricky to find all of the problems ahead of time. so tha ks a lot for reporting it. it was pretty critical
