### ISSUE TITLE
Run commands in exec/Get stdout from eval/Add some form of command substitution

### ISSUE THREAD

**Issue by JonahPlusPlus** [sagiegurari/duckscript#246]
### Feature Description
I've been trying to figure out how to get the output of `ls`, so I could split it into an array and do an operation on a bunch of files. I can't figure out how to do this with the current tools. I can't implement my own command cause this is for a makefile.toml (can I?). I wanted to avoid Rust for a simple task, but I guess I can't. Unless I missed something, but I poured over the documentation to no avail.

### Describe The Solution You'd Like
Allow for capturing stdout (and stderr?) of commands. I know eval is supposed to be the command equivalent for exec, so maybe it should have properties for stdout, stderr, and exitcode? Otherwise, could it use some form of command substitution like $( ) for capturing stdout?

Edit: Probably don't even need this right now, as I only have one file right now in that directory. But I still think it would be good if I was able to do this in a scripting language.

**Comment by sagiegurari** [comment]
if you want the output, you need to define an output var and use the stdout sub var.
from: https://github.com/sagiegurari/duckscript/blob/master/docs/sdk.md#std__process__Execute
```sh
output = exec ls
echo ${output.stdout}
echo ${output.stderr}
echo ${output.code}
```

however, if you want the list of files in a path as an array, why not use 'ls' command:
https://github.com/sagiegurari/duckscript/blob/master/docs/sdk.md#std__fs__List

or if you want a glob, you can use:
https://github.com/sagiegurari/duckscript/blob/master/docs/sdk.md#std__fs__GlobArray

**Comment by JonahPlusPlus** [comment]
`exec ls` is not cross-platform. For me, duckscript tries to run it in what I'm guessing is cmd.exe. Since cmd.exe does not have the ls command, it fails.

I want the list of files in a path as an array, but ls returns a bool, not a handle? I want to be able to capture the output that gets sent to the stdout of my terminal, but there seems to be no way of doing that in duckscript, at least documented.

GlobArray seems to be what I want, thanks. You might want to put a notice of this under ls, since in other script languages, ls is what I would turn to first for something simple as just getting all the files in a directory.

**Comment by sagiegurari** [comment]
no, there is ls command in duckscript without exec. its built in and returns a list.
did you look at the link i wrote?

**Comment by JonahPlusPlus** [comment]
Yeah, first, I should clarify, each paragraph I wrote referred to each of your solutions. Your first solution (exec) didn't work cause it looks for ls on the system, not the one provided. The second solution (the link to the built-in ls), doesn't work for me since it just returns true or false when I need the output of it which just prints to the terminal. I can't get stdout or an array from it.

**Comment by sagiegurari** [comment]
ok got it :)
happy you have a working solution.
