### ISSUE TITLE
mv file.rs new_file.rs does not work

### ISSUE THREAD

**Issue by burrbull** [sagiegurari/duckscript#319]
### Describe The Bug
According to docs 
```
mv ./file.rs ./new_file.rs
```
should rename file.
Instead of this it creates new `new_file.rs` directory and moves `file.rs` to `new_file.rs/file.rs`.

**Comment by sagiegurari** [comment]
i see I'm doing
fs::copy(source_path_str, target_path_str) which i figured would work correctly.
meaning dir path would be parent, file path would be actual target.
anyhow, would you like to PR it?

**Comment by burrbull** [comment]
In first view the issue should be in this line:
https://github.com/sagiegurari/duckscript/blob/43c175f3d66a04449ed92b43f465a9cdbbe66548/duckscript_sdk/src/sdk/std/fs/mv/mod.rs#L45

The [doc](https://doc.rust-lang.org/std/path/struct.Path.html#method.is_file) says that `is_file` return `true` only if file exists.

**Comment by sagiegurari** [comment]
ah right.... should have checked if ends with a separator / or \ instead

**Comment by burrbull** [comment]
https://github.com/sagiegurari/duckscript/pull/320

**Comment by sagiegurari** [comment]
@burrbull i've merged your PR (sorry for long wait) and will be releasing a new duckscript version in the next hours. thanks a lot for the help.
