### ISSUE TITLE
How to change a directory's name

### ISSUE THREAD

**Issue by Dirreke** [sagiegurari/duckscript#374]
### Feature Description
I have no idea about how to change a directory's name. 

 - It seem's like `mv` will move the source directory into the target directory.
 - `glob_cp source/* target/*`  is not available too.
 And I tried to use `for` to mv every entry in source to target. However,
- I have no idea about how to get the entry list in source. `ls` will return a bool value and no the entry in source.

So if there's some way to change the directory's name directly?

**Comment by sagiegurari** [comment]
@Dirreke looking at the code, i see indeed i didn't add support for that. woops.
you want maybe to PR that? the code is here:
https://github.com/sagiegurari/duckscript/blob/23958684d9568741c0f20486c581f9dd710c8f07/duckscript_sdk/src/sdk/std/fs/mv/mod.rs#L64

**Comment by sagiegurari** [comment]
@Dirreke this is now supported.
mv ./dir1 ./dir2
should work

**Comment by Dirreke** [comment]
Thanks! And I want to make PR later to support `ls` to return the array of the list content but not print them.

**Comment by sagiegurari** [comment]
@Dirreke sure. maybe add some --quite flag.... 
PRs are always welcome
