### ISSUE TITLE
`if eq` does not support empty strings

### ISSUE THREAD

**Issue by wmmc88** [sagiegurari/duckscript#390]
### Describe The Bug
This is similar to #47 , but this is when the empty string is part of a conditional statement like `if`.

### To Reproduce
This works:
```
e = eq "" ""
if ${e}
  # do stuff
end
```

This fails:
```
if eq "" ""
  # do stuff
end
```

### Error Stack

```console
ERROR - Error while running duckscript: Source: Unknown Line: 16 - Two arguments are required.
```

**Comment by sagiegurari** [comment]
hmm seems it breaking the if/else parsing....

**Comment by sagiegurari** [comment]
@wmmc88 this should be fixed now. thanks for reporting
