### ISSUE TITLE
WebAssembly

### ISSUE THREAD

**Issue by flip111** [sagiegurari/duckscript#391]
Does the compiler run on WebAssembly (wasm)? Is such feature planned?

**Comment by sagiegurari** [comment]
@flip111 i never tried to work with webassembly so i have no idea.
1. the duckscript parser/runtime should work just fine. it doesn't do anything special apart of running a script file which i'm not sure how thats supported
2. the sdk has lots of stuff to do with filesystem, network, etc.. which i'm not sure how that would be emulated in webassembly (for example if its run inside a browser).

so, i never really given much thought to it as i see webassembly mostly connected to browsers which already have a scripting lang which is way more powerful than this. And ya, i know you can use it outside of browsers, but i haven't seen much of that type of use.

whats the use case?

**Comment by flip111** [comment]
i was looking for a language that the user can run inside a browser and wanted to see if there are good alternatives to javascript

**Comment by flip111** [comment]
I'm also not sure

**Comment by sagiegurari** [comment]
closing for now.
