### ISSUE TITLE
Async embedded

### ISSUE THREAD

**Issue by nickheyer** [sagiegurari/duckscript#447]
### Feature Description

Currently facing an issue where running duckscript via `duckscript::runner::run_script` doesn't leave me a with a way to exit/abort from unfinished script execution. The invoked script will simply continue executing in the background (running in a `task::spawn_blocking`). I've tried a few different work arounds, and was able to kill my readers/writers attached to the Env, but not the actual script execution.

### Describe The Solution You'd Like

```sh
r = range 1 5
for x in ${r}
    echo "Iteration ${x}"
    sleep 1000
end
```
Would output:

```
Iteration 1
Iteration 2
Iteration 3 # <- I want to be able to terminate the script execution here from Rust
Iteration 4
Iteration 5 
# <- It currently terminates here
```

I think adding some type of method that I could call from the main thread to terminate the execution without exiting the entire program would be great (im running a ui on top of the interpreter).

**Comment by sagiegurari** [comment]
you can always add a goto :exit anywhere you want,  where exit is a label at the end of your file.
can you try to see if it solves it?

**Comment by nickheyer** [comment]
> you can always add a goto :exit anywhere you want,  where exit is a label at the end of your file.
> can you try to see if it solves it?

Maybe I didn't explain my issue well enough. I mean within the rust embedding of the run_script function, not the duck script itself. 

I need to kill the script early, as if the user has just hit control-c on a script execution.

**Comment by nickheyer** [comment]
An example use case that might make more sense. 

Imagine you are writing and running some duckscript in a virtual IDE/terminal on a webpage, like replit. You just clicked "RUN" with the below entered into the input:

```sh
r = range 1 99999999
for x in ${r}
    echo "Iteration ${x}"
    sleep 1000
end
```

Realizing this is going to take forever to complete, you want to cancel it by leaving the page. After leaving the page, the script will still be running in the background, consuming resources and doing potentially unintended things.
