### ISSUE TITLE
weird output for the 0.11.0 release build

### ISSUE THREAD

**Issue by chenrui333** [sagiegurari/duckscript#454]
👋 trying to build 0.11.0 release, but seeing the output is a bit weird. 

```diff
- assert_match "The out variable holds the value: Hello World", output
+ assert_match "Theoutvariableholdsthevalue:Hello World", output
```

relates to https://github.com/Homebrew/homebrew-core/pull/194315

**Comment by sagiegurari** [comment]
i am not involved in the homebrew release. can you guide me what this test is about?

**Comment by chenrui333** [comment]
> i am not involved in the homebrew release. can you guide me what this test is about?

I am the maintainer there, this test is just to test the artifact's functionality (as you can see the output is different btw the two releases, does it ring a bell?) Thanks!

**Comment by shakna-israel** [comment]
On the latest cargo build

    echo Hello World

Gives

    HelloWorld

**Comment by sagiegurari** [comment]
@shakna-israel thanks. horrible bug. i'm on it.

**Comment by sagiegurari** [comment]
@shakna-israel ok silly bug. found and fixed. i'm now pushing a new release

**Comment by sagiegurari** [comment]
should be solved now. thanks for reporting this!
closing the issue but feel free to reopen or open a new issue as needed

**Comment by chenrui333** [comment]
np, thanks for the quick fix.
