### ISSUE TITLE
Replace end_if, end_for, end_function with end keyword

### ISSUE THREAD

**Issue by mmstick** [sagiegurari/duckscript#53]
There's really no need to have a unique keyword for ending a scope. See [Ion](https://gitlab.redox-os.org/redox-os/ion)'s syntax as an example of what you can achieve with a single `end` keyword.

- [Functions](https://doc.redox-os.org/ion-manual/html/functions.html)
- [Loops](https://doc.redox-os.org/ion-manual/html/control/02-loops.html)
- [Conditionals](https://doc.redox-os.org/ion-manual/html/control/01-conditionals.html)
- [Matches](https://doc.redox-os.org/ion-manual/html/control/03-matches.html)

**Comment by sagiegurari** [comment]
will definitely check it. thanks a lot for feedback

**Comment by sagiegurari** [comment]
@mmstick this should be supported now :)
thanks for the feedback. i think it really improves the language

**Comment by mmstick** [comment]
Thanks, this is a huge improvement.
