### ISSUE TITLE
Get an array element by it's index.

### ISSUE THREAD

**Issue by YruamaLairba** [sagiegurari/duckscript#94]
**Features Description**
Since in can't found in README.md or sdk.md how to do it, i think it's a missing feature, so correct me if i'm wrong. I think getting an element by it's index is an essential feature of arrays, so i would be nice to have this ability.

**Describe the solution you'd like**
An array_get command should do the job.

**Comment by sagiegurari** [comment]
ya no problem.
my only concern is that people will start using that and write a for loop based on index instead of a forin on array elements. that would be a perf hit.
but.... its definitely a must core command and I'll add it.

thanks for the feedback

**Comment by sagiegurari** [comment]
this is now implemented and available in duckscript 0.3.2 version.
also added array_set.
thanks for the feedback and feel free to open more requests.
